name: csharp-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install tools
        run: npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli

      - name: Build codegen
        run: mvn clean install

      - name: Generate csharp source
        run: |
          openapi-generator-cli --custom-generator target/openapi-generator-gauge-plugin-1.0.0.jar generate -g csharp-gauge --package-name PetStore -i tests/petstore-extended.yaml -o out/csharp -p gaugeTargetHost=http://localhost:4010
          cp -r tests/specs out/csharp/src/PetStore.Test

      - name: Start Prism server
        run: prism mock tests/petstore-extended.yaml & sleep 15

      - name: Run gauge
        run: gauge run specs
        working-directory: out/csharp/src/PetStore.Test

      - name: Stop Prism server
        if: success() || failure()
        run: pkill -f prism
