name: go-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Install tools
        run: npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli

      - name: Build codegen
        run: mvn clean install

      - name: Generate go source
        run: |
          openapi-generator-cli --custom-generator target/openapi-generator-gauge-plugin-1.0.0.jar generate -g go-gauge --package-name PetStore -i tests/petstore-extended.yaml -o out/go -p gaugeTargetHost=http://localhost:4010
          cp -r tests/specs out/go

      - name: Start Prism server
        run: prism mock tests/petstore-extended.yaml & sleep 15

      - name: Get test dependencies
        run: go get -u -v all
        working-directory: out/go/test

      - name: Run test
        run: gauge run specs
        working-directory: out/go

      - name: Stop Prism server
        if: success() || failure()
        run: pkill -f prism
