name: go-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Install tools
        run: npm install -g @stoplight/prism-cli @openapitools/openapi-generator-cli

      - name: Generate go source
        run: |
          openapi-generator-cli generate -t templates/go -g go --package-name PetStore -i tests/petstore-extended.yaml -o out/go
          cp tests/*.feature out/go/test

      - name: Start Prism server
        run: prism mock tests/petstore-extended.yaml & sleep 15

      - name: Get test dependencies
        run: go get -u -v all
        working-directory: out/go/test

      - name: Run test
        run: go test
        working-directory: out/go/test

      - name: Stop Prism server
        if: success() || failure()
        run: pkill -f prism
