name: java-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14

      - name: Install tools
        run: |
          npm install -g @stoplight/prism-cli @openapitools/openapi-generator-cli @getgauge/cli
          sudo apt install maven -y

      - name: Generate java source
        run: |
          openapi-generator-cli generate -t codegen/java/templates -c codegen/java/config.yaml -g java --package-name PetStore -i tests/petstore-extended.yaml -o out/java
          cp -r tests/specs out/java

      - name: Setup gauge tests
        run: |
          chmod +x setup_gauge.sh
          ./setup_gauge.sh
        working-directory: out/java

      - name: Start Prism server
        run: prism mock tests/petstore-extended.yaml & sleep 15

      - name: Run Gradle test
        run: gradle gauge
        working-directory: out/java

      - name: Run Maven test
        run: mvn test-compile gauge:execute
        working-directory: out/java

      - name: Stop Prism server
        if: success() || failure()
        run: pkill -f prism
