name: java-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14

      - name: Install tools
        run: |
          npm install -g @stoplight/prism-cli @getgauge/cli
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.11.0/openapi-generator-cli-7.11.0.jar

      - name: Build codegen
        run: mvn clean install

      - name: Generate java source
        run: |
          java -cp target/gauge-codegen-1.0.0.jar:openapi-generator-cli-7.11.0.jar org.openapitools.codegen.OpenAPIGenerator generate -g java-gauge --package-name PetStore -i tests/petstore-extended.yaml -o out/java -p gaugeTargetHost=http://localhost:4010
          cp -r tests/specs out/java

      - name: Start Prism server
        run: prism mock tests/petstore-extended.yaml & sleep 15

      - name: Run Gradle test
        run: gradle gauge
        working-directory: out/java

      - name: Run Maven test
        run: mvn test-compile gauge:execute
        working-directory: out/java

      - name: Stop Prism server
        if: success() || failure()
        run: pkill -f prism
