name: python-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install tools
        run: npm install -g @stoplight/prism-cli @getgauge/cli @openapitools/openapi-generator-cli

      - name: Build codegen
        run: mvn clean install

      - name: Generate python source
        run: |
          openapi-generator-cli --custom-generator target/openapi-generator-gauge-plugin-1.0.0.jar generate -g python-gauge --package-name PetStore -i tests/petstore-extended.yaml -o out/python -p gaugeTargetHost=http://localhost:4010
          cp -r tests/specs out/python

      - name: Start Prism server
        run: prism mock tests/petstore-extended.yaml & sleep 15

      - name: Install test dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt -r test-requirements.txt
        working-directory: out/python

      - name: Run tests
        run: gauge run specs
        working-directory: out/python

      - name: Stop Prism server
        if: success() || failure()
        run: pkill -f prism
